/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RPSGUI.java
 *
 * Created on Apr 17, 2012, 10:28:48 PM
 */
package RockPaperScissors;

/**
 *
 * @author kqarlos
 */
public class RPSGUI extends javax.swing.JFrame {

    /** Creates new form RPSGUI */
    public RPSGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        north = new javax.swing.JPanel();
        scoresLabel = new javax.swing.JLabel();
        winsLabel = new javax.swing.JLabel();
        lossesLabel = new javax.swing.JLabel();
        tiesLabel = new javax.swing.JLabel();
        predicitonLabel = new javax.swing.JLabel();
        predictionField = new javax.swing.JTextField();
        winsField = new javax.swing.JTextField();
        tiesField = new javax.swing.JTextField();
        lossesField = new javax.swing.JTextField();
        west = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        difficultyList = new javax.swing.JList();
        difficultyLabel = new javax.swing.JLabel();
        roundInputLabel = new javax.swing.JLabel();
        RoundInputTextField = new javax.swing.JTextField();
        south = new javax.swing.JPanel();
        weaponsLabel = new javax.swing.JLabel();
        rockButton = new javax.swing.JButton();
        paperButton = new javax.swing.JButton();
        scissorsButton = new javax.swing.JButton();
        optionsLabel = new javax.swing.JLabel();
        helpButton = new javax.swing.JButton();
        east = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayerMain = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scoresLabel.setText("SCORES");

        winsLabel.setText("Wins:");

        lossesLabel.setText("Losses:");

        tiesLabel.setText("Ties:");

        predicitonLabel.setText("CURRENT PREDICITON:");

        predictionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                predictionFieldActionPerformed(evt);
            }
        });

        winsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winsFieldActionPerformed(evt);
            }
        });

        tiesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiesFieldActionPerformed(evt);
            }
        });

        lossesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lossesFieldActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout northLayout = new org.jdesktop.layout.GroupLayout(north);
        north.setLayout(northLayout);
        northLayout.setHorizontalGroup(
            northLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(northLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(northLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(scoresLabel)
                    .add(predicitonLabel))
                .add(28, 28, 28)
                .add(northLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(northLayout.createSequentialGroup()
                        .add(winsLabel)
                        .add(18, 18, 18)
                        .add(winsField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(predictionField))
                .add(32, 32, 32)
                .add(lossesLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lossesField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(44, 44, 44)
                .add(tiesLabel)
                .add(18, 18, 18)
                .add(tiesField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        northLayout.setVerticalGroup(
            northLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(northLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(northLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(scoresLabel)
                    .add(winsLabel)
                    .add(winsField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lossesLabel)
                    .add(lossesField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tiesLabel)
                    .add(tiesField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(northLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(northLayout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(predicitonLabel))
                    .add(northLayout.createSequentialGroup()
                        .add(14, 14, 14)
                        .add(predictionField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(north, java.awt.BorderLayout.PAGE_START);

        difficultyList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(difficultyList);

        difficultyLabel.setText("DIFFICULTY:");

        roundInputLabel.setText("Number of Rounds:");

        RoundInputTextField.setText("Enter Number of Rounds ...");

        org.jdesktop.layout.GroupLayout westLayout = new org.jdesktop.layout.GroupLayout(west);
        west.setLayout(westLayout);
        westLayout.setHorizontalGroup(
            westLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(westLayout.createSequentialGroup()
                .add(westLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(westLayout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(westLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jScrollPane1)
                            .add(westLayout.createSequentialGroup()
                                .add(difficultyLabel)
                                .add(30, 30, 30))
                            .add(RoundInputTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(westLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(roundInputLabel)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        westLayout.setVerticalGroup(
            westLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(westLayout.createSequentialGroup()
                .add(30, 30, 30)
                .add(difficultyLabel)
                .add(14, 14, 14)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(roundInputLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(RoundInputTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(176, 176, 176))
        );

        getContentPane().add(west, java.awt.BorderLayout.LINE_START);

        weaponsLabel.setText("WEAPONS:");
        south.add(weaponsLabel);

        rockButton.setText("ROCK");
        rockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockButtonActionPerformed(evt);
            }
        });
        south.add(rockButton);

        paperButton.setText("PAPER");
        south.add(paperButton);

        scissorsButton.setText("SCISSORS");
        south.add(scissorsButton);

        optionsLabel.setText("OPTIONS:");
        south.add(optionsLabel);

        helpButton.setText("HELP");
        south.add(helpButton);

        getContentPane().add(south, java.awt.BorderLayout.PAGE_END);

        org.jdesktop.layout.GroupLayout eastLayout = new org.jdesktop.layout.GroupLayout(east);
        east.setLayout(eastLayout);
        eastLayout.setHorizontalGroup(
            eastLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        eastLayout.setVerticalGroup(
            eastLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 304, Short.MAX_VALUE)
        );

        getContentPane().add(east, java.awt.BorderLayout.LINE_END);

        displayerMain.setColumns(20);
        displayerMain.setRows(5);
        jScrollPane2.setViewportView(displayerMain);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rockButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rockButtonActionPerformed

    private void predictionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_predictionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_predictionFieldActionPerformed

    private void winsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_winsFieldActionPerformed

    private void tiesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiesFieldActionPerformed

    private void lossesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lossesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lossesFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RPSGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RoundInputTextField;
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JList difficultyList;
    private javax.swing.JTextArea displayerMain;
    private javax.swing.JPanel east;
    private javax.swing.JButton helpButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lossesField;
    private javax.swing.JLabel lossesLabel;
    private javax.swing.JPanel north;
    private javax.swing.JLabel optionsLabel;
    private javax.swing.JButton paperButton;
    private javax.swing.JLabel predicitonLabel;
    private javax.swing.JTextField predictionField;
    private javax.swing.JButton rockButton;
    private javax.swing.JLabel roundInputLabel;
    private javax.swing.JButton scissorsButton;
    private javax.swing.JLabel scoresLabel;
    private javax.swing.JPanel south;
    private javax.swing.JTextField tiesField;
    private javax.swing.JLabel tiesLabel;
    private javax.swing.JLabel weaponsLabel;
    private javax.swing.JPanel west;
    private javax.swing.JTextField winsField;
    private javax.swing.JLabel winsLabel;
    // End of variables declaration//GEN-END:variables
}
